services:
  db:
    image: postgres:16-alpine
    container_name: shopdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/shopdb
      PORT: 4000
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: web
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
